#!/bin/bash

## ########################################################################## ##
##
## init
##
## ########################################################################## ##

## includes
source ../lib/func_script-handling

## -------------------------------------------------------------------------- ##
## DEFINITIONS:
## -------------------------------------------------------------------------- ##
CALLEE="false"

## -------------------------------------------------------------------------- ##
## select release tag:
SYSTEM_i686=$((0x01))
SYSTEM_x86_64=$((0x02))
# ------------------
## system architecture selection:
SYSTEM_ARCHITECTURE=${SYSTEM_x86_64}
#SYSTEM_ARCHITECTURE=${SYSTEM_i686}

## -------------------------------------------------------------------------- ##
## select release tag:
##  example:
##  retrieve all tags that match the specified pattern:
##  - git tag -l "v6.7.*"
##  - set the desired release tag
##  create (if necessary) and then switch to a new local branch based on tag:
##  - will be done by func_git_switch_to_working_branch
##    (called by 00-script-set-kernel-repository-default.sh)
#RELEASE_TAG="v6.7.5"
#RELEASE_TAG="v6.12.8"
#RELEASE_TAG="v6.15.2"
#RELEASE_TAG="v7.0.6"        ## 2026.05.12 stable:   7.0.6
#RELEASE_TAG="v7.0.9"        ## 2026.05.17 stable:   7.0.9
RELEASE_TAG="v7.0.11"        ## 2026.06.01 stable:   7.0.11

## -------------------------------------------------------------------------- ##
LAYER_NO="0"

## ########################################################################## ##

